CREATE DATABASE minhasaude;

CREATE TABLE usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    tipo ENUM('ADMIN', 'DEFAULT') NOT NULL,
    senha TEXT NOT NULL
);

